# Inleiding tot Tensors met PyTorch

Deze notebook behandelt de basis van tensors met behulp van het PyTorch-framework. We zullen bespreken wat tensors zijn, hoe we ze kunnen maken, indexeren, de gegevens erin kunnen manipuleren en de vorm ervan kunnen wijzigen. Elk gedeelte bevat enkele oefeningen om uw begrip te testen.

## Wat zijn Tensors

Tensors zijn een fundamentele gegevensstructuur in veel machine learning-frameworks, waaronder PyTorch. Ze zijn vergelijkbaar met arrays en matrices, maar zijn gegeneraliseerd naar hogere dimensies. Ze kunnen worden gebruikt om verschillende soorten gegevens te vertegenwoordigen, zoals vectors, matrices en zelfs hogere-dimensionale gegevens.

Een tensor kan worden beschouwd als een meerdimensionale array. Tensors kunnen een willekeurig aantal dimensies hebben, en elke dimensie wordt een as genoemd. Hier zijn enkele voorbeelden van tensors van verschillende dimensies:
- Een scalair is een 0-dimensionale tensor.
- Een vector is een 1-dimensionale tensor.
- Een matrix is een 2-dimensionale tensor.
- Een tensor van hogere orde kan drie of meer dimensies hebben.

In [1]:
import torch

# Voorbeeld van een scalair
scalar = torch.tensor(5)
print(scalar)

# Voorbeeld van een vector
vector = torch.tensor([1, 2, 3])
print(vector)

# Voorbeeld van een matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)

# Voorbeeld van een tensor van hogere orde
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)

tensor(5)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## Hoe maak je Tensors

In PyTorch kunnen tensors op verschillende manieren worden gemaakt, bijvoorbeeld door gebruik te maken van torch.tensor(), of door gebruik te maken van functies zoals torch.zeros(), torch.ones(), en torch.arange().

In [2]:
# Een tensor maken van een lijst
a = torch.tensor([1, 2, 3])
print(a)

# Een tensor maken gevuld met nullen
b = torch.zeros(2, 3)
print(b)

# Een tensor maken gevuld met enen
c = torch.ones(4)
print(c)

# Een tensor maken met een range van waarden
d = torch.arange(0, 10, 2)
print(d)


tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1., 1., 1., 1.])
tensor([0, 2, 4, 6, 8])


### Oefening

Maak de volgende tensors:

* Een scalair met de waarde 7.
* Een vector met de waarden [10, 20, 30, 40].
* Een matrix met de waarden [[1, 2], [3, 4], [5, 6]].
* Een 3-dimensionale tensor met de waarden [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]].
* Een tensor met random waarden met dezelfde shape als de vorige tensor. Tip: rand_like
* Een tensor gevuld met nullen met de vorm (3, 2).
* Een tensor gevuld met enen met de vorm (2, 2, 2).
* Een tensor met de waarden van 0 tot 9.
* Een tensor met willekeurige waarden met de vorm (3, 3).

In [ ]:
import torch

# 1. Een scalair met de waarde 7.
scalar_tensor = torch.tensor(7)
print("Scalar:", scalar_tensor)

# 2. Een vector met de waarden [10, 20, 30, 40].
vector_tensor = torch.tensor([10, 20, 30, 40])
print("Vector:", vector_tensor)

# 3. Een matrix met de waarden [[1, 2], [3, 4], [5, 6]].
matrix_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("Matrix:", matrix_tensor)

# 4. Een 3-dimensionale tensor met de waarden [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]].
three_d_tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("3D Tensor:", three_d_tensor)

# 5. Een tensor met random waarden met dezelfde shape als de vorige tensor.
random_like_tensor = torch.rand_like(three_d_tensor, dtype=torch.float)
print("Random Tensor (same shape as 3D Tensor):", random_like_tensor)

# 6. Een tensor gevuld met nullen met de vorm (3, 2).
zeros_tensor = torch.zeros((3, 2))
print("Zeros Tensor (shape (3, 2)):", zeros_tensor)

# 7. Een tensor gevuld met enen met de vorm (2, 2, 2).
ones_tensor = torch.ones((2, 2, 2))
print("Ones Tensor (shape (2, 2, 2)):", ones_tensor)

# 8. Een tensor met de waarden van 0 tot 9.
range_tensor = torch.arange(0, 10)
print("Range Tensor (0 to 9):", range_tensor)

# 9. Een tensor met willekeurige waarden met de vorm (3, 3).
random_tensor = torch.rand((3, 3))
print("Random Tensor (shape (3, 3)):", random_tensor)


# Hoe indexeer je Tensors

Net zoals arrays kunnen tensors worden geïndexeerd om specifieke elementen of delen van de tensor op te halen. Je kunt slicing en integer indexing gebruiken om elementen of sub-tensors te verkrijgen.

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Een element ophalen
print(tensor[0, 0])  # Output: 1

# Een rij ophalen
print(tensor[0, :])  # Output: [1, 2, 3]

# Een kolom ophalen
print(tensor[:, 1])  # Output: [2, 5, 8]

# Een sub-tensor ophalen
print(tensor[1:, 1:])  # Output: [[5, 6], [8, 9]]


### Oefening

Gegeven de tensor t = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), haal de volgende elementen op:

* Het element in de eerste rij en derde kolom.
* De tweede rij.
* De tweede kolom.
* Het sub-tensor bestaande uit de laatste twee rijen en de laatste twee kolommen.

In [ ]:
import torch

# Gegeven tensor
t = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Tensor t:\n", t)

# 1. Het element in de eerste rij en derde kolom.
element_1_3 = t[0, 2]  # Rijen en kolommen worden 0-gebaseerd geïndexeerd
print("\nElement in de eerste rij en derde kolom:", element_1_3)

# 2. De tweede rij.
second_row = t[1]  # Haalt de tweede rij op (index 1)
print("\nDe tweede rij:", second_row)

# 3. De tweede kolom.
second_column = t[:, 1]  # Haalt de tweede kolom op (alle rijen, kolom index 1)
print("\nDe tweede kolom:", second_column)

# 4. Het sub-tensor bestaande uit de laatste twee rijen en de laatste twee kolommen.
sub_tensor = t[1:, 1:]  # Start bij de tweede rij en tweede kolom
print("\nSub-tensor (laatste twee rijen en laatste twee kolommen):\n", sub_tensor)


## Hoe manipuleer je de gegevens in Tensors

Je kunt de waarden in een tensor manipuleren door middel van elementgewijze operaties, zoals optellen, aftrekken, vermenigvuldigen en delen.

In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Optellen
c = a + b
print(c)

# Aftrekken
d = a - b
print(d)

# Vermenigvuldigen
e = a * b
print(e)

# Delen
f = a / b
print(f)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


### Oefening

Gegeven de tensors x = torch.tensor([10, 20, 30]) en y = torch.tensor([1, 2, 3]), voer de volgende bewerkingen uit:

* Tel x en y op.
* Trek y af van x.
* Vermenigvuldig x met y (element gewijs).
* Deel x door y.
* Voeg de x en y tensors samen tot een tensor met shape (2, 3). Tip: cat
* Vermenigvulding x met de getransponeerde van y (matrixvermenigvuldiging). Tip: operator @ en matmul

In [ ]:
import torch

# Gegeven tensors
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

# 1. Tel x en y op.
sum_xy = x + y
print("x + y:", sum_xy)

# 2. Trek y af van x.
sub_xy = x - y
print("x - y:", sub_xy)

# 3. Vermenigvuldig x met y (element gewijs).
mul_xy = x * y
print("x * y (elementwise):", mul_xy)

# 4. Deel x door y.
div_xy = x / y
print("x / y (elementwise):", div_xy)

# 5. Voeg de x en y tensors samen tot een tensor met shape (2, 3).
concat_xy = torch.cat((x.unsqueeze(0), y.unsqueeze(0)), dim=0)
print("Concatenated tensor (shape (2, 3)):\n", concat_xy)

# 6. Vermenigvuldiging van x met de getransponeerde van y (matrixvermenigvuldiging).
matmul_xy = x @ y.T  # matrixvermenigvuldiging (dot product)
print("x @ y (matrix multiplication):", matmul_xy)


## Hoe manipuleer je de vorm van Tensors

De vorm van een tensor kan worden veranderd met behulp van functies zoals reshape(), view() en transpose().

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Herschikken van de tensor naar een andere vorm
reshaped_tensor = tensor.reshape(3, 2)
print(reshaped_tensor)

# De tensor transponeren
transposed_tensor = tensor.t()
print(transposed_tensor)


### Oefening

Gegeven de tensor z = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]]), voer de volgende bewerkingen uit:

* Herschik de tensor naar de vorm (4, 2).
* Transponeer de tensor.
* Herschik de tensor naar een 1-dimensionale tensor met 8 elementen.
* Voeg een extra dimensie aan de originele z-vector toe zodat de shape (1,2,4) is. Tip: unsqueeze

In [ ]:
import torch

# Gegeven tensor
z = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Originele tensor z:\n", z)

# 1. Herschik de tensor naar de vorm (4, 2).
reshaped_tensor = z.view(4, 2)
print("\nHerschikte tensor (shape (4, 2)):\n", reshaped_tensor)

# 2. Transponeer de tensor.
transposed_tensor = z.t()
print("\nGetransponeerde tensor (shape (4, 2)):\n", transposed_tensor)

# 3. Herschik de tensor naar een 1-dimensionale tensor met 8 elementen.
flattened_tensor = z.view(-1)  # Of: z.flatten()
print("\nHerschikte tensor naar een 1-dimensionale tensor (8 elementen):\n", flattened_tensor)

# 4. Voeg een extra dimensie toe zodat de shape (1, 2, 4) is.
unsqueezed_tensor = z.unsqueeze(0)  # Voeg een extra dimensie toe aan de eerste positie
print("\nTensor met extra dimensie (shape (1, 2, 4)):\n", unsqueezed_tensor)